version: "2"
services:
  web:
    build: .
    image: ctfhub/base_web_flask_python_36
    ports:
      - "8085:80"
    environment:
      - FLAG=ctfhub{base_web_flask_python_36}
      - FLASK_APP=app
      - FLASK_ENV=development
